import { Reloj } from "../interfaces/lista_relojes.interface";

export const RELOJES: Reloj[] = [
    {
        id: 1,
        marca: 'Rolex',
        familia: 'Datejust 36',
        modelo: 'Datejust 36',
        material: 'Stainless Steel',
        cristal: 'Sapphire',
        diametro: 36,
        color: 'Blue',
        año: 2020,
        imagen: 'https://cdn.watchbase.com/watch/lg/origin:png/rolex/datejust/116200-0057-bc.webp',
        disponibilidad: "Si",
        descripcion: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem nihil sit temporibus voluptatibus at laborum, eos tempore aperiam nesciunt, dolore odit! Voluptate dolorem deleniti temporibus consequatur asperiores ullam voluptatem sed."
    },
    {
        id: 2,
        marca: 'Rolex',
        familia: 'Submariner',
        modelo: 'Submariner Date',
        material: 'Stainless Steel',
        cristal: 'Sapphire',
        diametro: 40,
        color: 'Green',
        año: 2010,
        imagen: 'https://cdn.watchbase.com/watch/lg/origin:png/rolex/submariner/116610lv-0002-c1.webp',
        disponibilidad: "Si",
        descripcion: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem nihil sit temporibus voluptatibus at laborum, eos tempore aperiam nesciunt, dolore odit! Voluptate dolorem deleniti temporibus consequatur asperiores ullam voluptatem sed."
    },
    {
        id: 3,
        marca: 'Omega',
        familia: 'Speedmaster',
        modelo: 'Speedmaster Professional Moonwatch 3861',
        material: 'Stainless Steel',
        cristal: 'Plexi',
        diametro: 42,
        color: 'Black',
        año: 2021,
        imagen: 'https://cdn.watchbase.com/watch/lg/origin:jpg/omega/speedmaster/310-30-42-50-01-001-a2.webp',
        disponibilidad: "Si",
        descripcion: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem nihil sit temporibus voluptatibus at laborum, eos tempore aperiam nesciunt, dolore odit! Voluptate dolorem deleniti temporibus consequatur asperiores ullam voluptatem sed."
    },
    {
        id: 4,
        marca: 'Omega',
        familia: 'De Ville',
        modelo: 'De Ville Prestige Automatic',
        material: 'Yellow gold',
        cristal: 'Sapphire',
        diametro: 34.7,
        color: 'Champagne',
        año: 2018,
        imagen: 'https://cdn.watchbase.com/watch/lg/origin:png/omega/de-ville/4600-11-02-25.webp',
        disponibilidad: "Si",
        descripcion: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem nihil sit temporibus voluptatibus at laborum, eos tempore aperiam nesciunt, dolore odit! Voluptate dolorem deleniti temporibus consequatur asperiores ullam voluptatem sed."
    },
    {
        id: 5,
        marca: 'Apple',
        familia: 'Apple',
        modelo: 'Watch sport blue',
        material: 'Ceramic',
        cristal: 'Ion-X',
        diametro: 35.9,
        color: 'Blue',
        año: 2015,
        imagen: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MJK53_VW_34FR+watch-44-alum-silver-nc-6s_VW_34FR_WF_CO_GEO_ES?wid=750&hei=712&trim=1,0&fmt=p-jpg&qlt=95&.v=1617728050000,1601923080000',
        disponibilidad: "Si",
        descripcion: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem nihil sit temporibus voluptatibus at laborum, eos tempore aperiam nesciunt, dolore odit! Voluptate dolorem deleniti temporibus consequatur asperiores ullam voluptatem sed."
    },
    {
        id: 6,
        marca: 'Cartier',
        familia: 'Calibre de Cartier',
        modelo: 'Calibre de Cartier 42',
        material: 'Stainless Steel',
        cristal: 'Sapphire',
        diametro: 42,
        color: 'Silver',
        año: 2011,
        imagen: 'https://cdn.watchbase.com/watch/lg/origin:png/cartier/calibre-de-cartier/w7100015-a1.webp',
        disponibilidad: "Si",
        descripcion: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem nihil sit temporibus voluptatibus at laborum, eos tempore aperiam nesciunt, dolore odit! Voluptate dolorem deleniti temporibus consequatur asperiores ullam voluptatem sed."
    },
    {
        id: 7,
        marca: 'Cartier',
        familia: 'Calibre de Cartier',
        modelo: 'Calibre de Cartier Diver',
        material: 'Stainless Steel',
        cristal: 'Sapphire',
        diametro: 42,
        color: 'Blue',
        año: 2013,
        imagen: 'https://cdn.watchbase.com/watch/lg/origin:png/cartier/calibre-de-cartier/w2ca0009-16.webp',
        disponibilidad: "Si",
        descripcion: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem nihil sit temporibus voluptatibus at laborum, eos tempore aperiam nesciunt, dolore odit! Voluptate dolorem deleniti temporibus consequatur asperiores ullam voluptatem sed."
    },
    {
        id: 8,
        marca: 'TAG Heuer',
        familia: 'Formula 1',
        modelo: 'Quartz Chronograph Big Date 44',
        material: 'Stainless Steel',
        cristal: 'Sapphire',
        diametro: 44,
        color: 'White',
        año: 2019,
        imagen: 'https://cdn.watchbase.com/watch/lg/origin:jpg/tag-heuer/formula-1/cah1011ba0860-90.webp',
        disponibilidad: "Si",
        descripcion: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem nihil sit temporibus voluptatibus at laborum, eos tempore aperiam nesciunt, dolore odit! Voluptate dolorem deleniti temporibus consequatur asperiores ullam voluptatem sed."
    },
    {
        id: 9,
        marca: 'TAG Heuer',
        familia: 'Formula 1',
        modelo: ':Quartz Chronograph 41',
        material: 'Stainless Steel',
        cristal: 'Sapphire',
        diametro: 41,
        color: 'Red',
        año: 2015,
        imagen: 'https://cdn.watchbase.com/watch/lg/origin:jpg/tag-heuer/formula-1/cah1112ba0850-55.webp',
        disponibilidad: "Si",
        descripcion: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem nihil sit temporibus voluptatibus at laborum, eos tempore aperiam nesciunt, dolore odit! Voluptate dolorem deleniti temporibus consequatur asperiores ullam voluptatem sed."
    },
    {
        id: 10,
        marca: 'Longines',
        familia: 'La Grande Classique',
        modelo: 'Presence 40 Small',
        material: 'Stainless Steel',
        cristal: 'Sapphire',
        diametro: 40,
        color: 'White',
        año: 2019,
        imagen: 'https://cdn.watchbase.com/watch/lg/origin:jpg/longines/la-grande-classique/l4-905-4-11-2-a.webp',
        disponibilidad: "Si",
        descripcion: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem nihil sit temporibus voluptatibus at laborum, eos tempore aperiam nesciunt, dolore odit! Voluptate dolorem deleniti temporibus consequatur asperiores ullam voluptatem sed."
    },

]